### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by aminya**
- This updates the dependencies
- Replaces the wrapper functions with the original function if it is provided by the package.
- Replaced deprecated/old packages with better alternatives: find -> fast-glob, rimraft -> fsExtra, splitargs -> splitargs2
- The large code change number is just because npm 7 stores more information inside the package-lock.json

Closes #3
Closes #4
Closes #5
Closes #6
Closes #7

### CODE REVIEW

**Comment by aminya** [comment]
@martin31821 Could you check this out? 😃

**Comment by martin31821** [comment]
Looks good so far, I'll double check whether it breaks things for my projects and then get back to you.

**Comment by aminya** [comment]
Thank you! If you can add an example project, we can use it as a test for the functionality, which can prevent unintentional breakages.

**Comment by aminya** [comment]
@martin31821 I can take over this repository to help with maintenance and development. I am having a lot of issues with node-gyp and cmake-js that are hard to debug, and I prefer to use a better tool instead of building upon a bad design.

**Comment by martin31821** [comment]
published both as 1.1.14

**Comment by aminya** [comment]
Thanks! I cannot find the commits that bump the package.json. Did you push them? Also, a Github tag should be created.

**Comment by martin31821** [comment]
> Thanks! I cannot find the commits that bump the package.json. Did you push them? Also, a Github tag should be created.

True, forgot to push the version bump, sorry. (Also, please check your inbox, I sent you an email)

**Pull request merged**
